---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: docker:ffdd-debian9
  image: debian:9
  commands:
    - echo 'deb http://deb.debian.org/debian unstable main' >> /etc/apt/sources.list
    - cd .ci
    - cp limit-unstable /etc/apt/preferences.d/limit-unstable
    - bash install_deps.sh
    - bash build_uci.sh

- name: docker:ffdd-debian10
  image: debian:10
  commands:
    - echo 'deb http://deb.debian.org/debian unstable main' >> /etc/apt/sources.list
    - cd .ci
    - cp limit-unstable /etc/apt/preferences.d/limit-unstable
    - bash install_deps.sh
    - bash build_uci.sh

- name: docker:ffdd-debian11
  image: debian:11
  commands:
    - echo 'deb http://deb.debian.org/debian unstable main' >> /etc/apt/sources.list
    - cd .ci
    - cp limit-unstable /etc/apt/preferences.d/limit-unstable
    - bash install_deps.sh
    - bash build_uci.sh

- name: docker:ffdd-ubuntu1804
  image: ubuntu:18.04
  commands:
    - cd .ci
    - bash install_deps.sh
    - bash build_uci.sh

- name: docker:ffdd-ubuntu2004
  image: ubuntu:20.04
  commands:
    - cd .ci
    - bash install_deps.sh
    - bash build_uci.sh


---
kind: pipeline
name: deploy

platform:
  os: linux
  arch: amd64

steps:
- name: ffdd-debian9-staging
  image: drillster/drone-rsync
  settings:
    hosts:
      from_secret: HOST
    port:
      from_secret: PORT
    key:
      from_secret: SSH_PRIVATE_KEY
    user:
      from_secret: USER
    source: .ci/build/*
    target: /home/deploy-server/html/packages/debian9/
    recursive: false
    delete: false

- name: ffdd-debian10-staging
  image: debian:11
  environment:
    HOST:
      from_secret: HOST
    PORT:
      from_secret: PORT
    RPATH:
      from_secret: RPTAH
    SSH_PRIVATE_KEY:
      from_secret: SSH_PRIVATE_KEY
    USER:
      from_secret: USER
  commands:
    - apt-get update -y && apt-get install -y openssh-client rsync
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh ; chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts
    - rsync -avz -e "ssh -p $PORT" .ci/build/* "$USER"@"$HOST":"$RPATH"/debian10/

- name: ffdd-debian11-staging
  image: debian:11
  environment:
    HOST:
      from_secret: HOST
    PORT:
      from_secret: PORT
    RPATH:
      from_secret: RPTAH
    SSH_PRIVATE_KEY:
      from_secret: SSH_PRIVATE_KEY
    USER:
      from_secret: USER
  commands:
    - apt-get update -y && apt-get install -y openssh-client rsync
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh ; chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts
    - rsync -avz -e "ssh -p $PORT" .ci/build/* "$USER"@"$HOST":"$RPATH"/debian11/

- name: ffdd-ubuntu1804-staging
  image: debian:11
  environment:
    HOST:
      from_secret: HOST
    PORT:
      from_secret: PORT
    RPATH:
      from_secret: RPTAH
    SSH_PRIVATE_KEY:
      from_secret: SSH_PRIVATE_KEY
    USER:
      from_secret: USER
  commands:
    - apt-get update -y && apt-get install -y openssh-client rsync
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh ; chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts
    - rsync -avz -e "ssh -p $PORT" .ci/build/* "$USER"@"$HOST":"$RPATH"/ubuntu18/

- name: ffdd-ubuntu2004-staging
  image: debian:11
  environment:
    HOST:
      from_secret: HOST
    PORT:
      from_secret: PORT
    RPATH:
      from_secret: RPTAH
    SSH_PRIVATE_KEY:
      from_secret: SSH_PRIVATE_KEY
    USER:
      from_secret: USER
  commands:
    - apt-get update -y && apt-get install -y openssh-client rsync
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh ; chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts
    - rsync -avz -e "ssh -p $PORT" .ci/build/* "$USER"@"$HOST":"$RPATH"/ubuntu20/

depends_on:
- build

...
