#!/usr/bin/env bash
### This file managed by Salt, do not edit by hand! ###
# modifies config to match firmware requirements

print_help() {
	printf 'usage: gen-config.sh config-file\n'
	printf '  or: gen-config.sh vpn1 config-file\n'
	exit 1
}

vpn0_set() {
	vpn='vpn0'
	CONF='/etc/openvpn/openvpn.conf'
}

vpn1_set() {
	vpn='vpn1'
	CONF='/etc/openvpn/openvpn1.conf'
}

test -z "$1" && print_help


if [ "$#" == '2' ]; then
	input="$2"
	if [ "$1" == 'vpn0' ]; then
		vpn0_set
	elif [ "$1" == 'vpn1' ]; then
		vpn1_set
	else
		print_help
	fi
elif [ "$#" == '1' ]; then
	input="$1"
	vpn0_set
else
	print_help
fi


printf '#generated by FFDD gen-config.sh\n' > "$CONF"

cat "$input" | sed '
s#^[	 ]*##
s/#.*$//
s#[ 	]*$##
/^$/d
/^#/d
/^dev/d
/^persist-key/d
/^persist-tun/d
/^keepalive/d
/^verb/d
/^script/d
/^up/d
/^down/d
/^route/d
/^ifconfig/d
/^resolv/d
/^float/d
/^dhcp-renew/d
/^dhcp-release/d
/^explicit-exit-notify/d
/^ping/d
/^pull-filter/d
/^auth-nocache/d
s#^auth-user-pass.*#auth-user-pass openvpn.login#
' >> "$CONF"

#add newline
cat<<EOM >> "$CONF"

dev $vpn
dev-type tun
resolv-retry infinite
keepalive 10 30
script-security 2
auth-nocache
float
route-noexec
ifconfig-noexec
up /etc/openvpn/up.sh 
down /etc/openvpn/down.sh
verb 3
EOM
